version: '3'
services:
  web:
    build: .
    command: 
      sh -c "alembic upgrade head && cd src && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    container_name: chat_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      -.env-non-dev
  
  db:
    image: postgres:15
    container_name: chat_db
    env_file:
      -.env-non-dev

  redis:
    image: redis:latest
    container_name: chat_redis

  celery:
    build:
      context: .
    container_name: chat_celery
    command: 
      sh -c "celery -A src.celery_config.celery_app worker --loglevel=info"
    depends_on:
      - redis
    env_file:
      -.env-non-dev
