"""update user model

Revision ID: 8114b4f4f983
Revises: 61687bbf639c
Create Date: 2024-10-26 11:16:30.391237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8114b4f4f983'
down_revision: Union[str, None] = '61687bbf639c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Сообщения',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Сообщения_id'), 'Сообщения', ['id'], unique=False)
    op.create_index(op.f('ix_Сообщения_timestamp'), 'Сообщения', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Сообщения_timestamp'), table_name='Сообщения')
    op.drop_index(op.f('ix_Сообщения_id'), table_name='Сообщения')
    op.drop_table('Сообщения')
    # ### end Alembic commands ###
